name: First workflow
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Test job welcome message
              run: echo "Executing the test job"

            - name: Checkout repository
              uses: actions/checkout@v5.0.1

            - name: ReadME file content
              run: cat README.md 